domain:
  domain_primitive:
    max_length_of_name: 50
    max_length_of_title: 50
    max_length_of_email: 100
    max_length_of_account: 100
    max_length_of_corp_name: 50

mongodb:
  db:
    conn: "{MONGODB_CONNECTION}"
    db: "${MONGODB_NAME}"
    ca_file: ./mongodb_ca.crt
  collections: 
    link: link
    corp_signing: corp_signing
    individual_signing: individual_signing

symmetric:
  encryption_key: "{SYMMETRIC_ENCRYPTION_KEY}"
